version: '3.3'

services:

  db:
    image: postgres:12.1
    restart: always
    ports:
        - "${PG_PORT}:${PG_PORT}"
    volumes:
        - "./docker/db/init:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
  
  app:
    build:
      context: ./
      dockerfile: "./docker/app/Dockerfile"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db